x-environment: &seed-nodes-environment
  SEED_PORT: 2551
  SEED_NODES.0: "akka://write-api-server@write-api-server-node1:2551"
  SEED_NODES.1: "akka://write-api-server@write-api-server-node2:2551"
  SEED_NODES.2: "akka://write-api-server@write-api-server-node3:2551"

services:
  write-api-server-node1:
    image: cqrs-es-example-write-api-server
    container_name: write-api-server-node1
    platform: linux/arm64
    environment:
      <<: *seed-nodes-environment
      SEED_HOSTNAME: write-api-server-node1
    ports:
      - "8080:8080"
    depends_on:
      dynamosetup:
        condition: service_completed_successfully
    networks:
      - backend-network

  write-api-server-node2:
    image: cqrs-es-example-write-api-server
    container_name: write-api-server-node2
    platform: linux/arm64
    environment:
      <<: *seed-nodes-environment
      SEED_HOSTNAME: write-api-server-node2
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    depends_on:
      dynamosetup:
        condition: service_completed_successfully
    networks:
      - backend-network

  write-api-server-node3:
    image: cqrs-es-example-write-api-server
    container_name: write-api-server-node3
    platform: linux/arm64
    environment:
      <<: *seed-nodes-environment
      SEED_HOSTNAME: write-api-server-node3
      SERVER_PORT: 8082
    ports:
      - "8082:8082"
    depends_on:
      dynamosetup:
        condition: service_completed_successfully
    networks:
      - backend-network

  dynamodb:
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb
    expose:
      - "8000"
    ports:
      - 8000:8000
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    volumes:
      - ./write-api-server/target/persistence/dynamodb/data:/data
    networks:
      - backend-network

  dynamodb-admin:
    container_name: dynamodb-admin
    image: aaronshaf/dynamodb-admin:latest
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb:8000
    ports:
      - 8001:8001
    depends_on:
      - dynamodb
    networks:
      - backend-network

  dynamosetup:
    image: infrastructureascode/aws-cli
    env_file:
      - ./.env/.env.test
    environment:
      LOCALSTACK_HOST: "dynamodb"
      DDB_PORT: 8000
    entrypoint: /scripts/dynamodb/entrypoint.sh
    volumes:
      - "./write-api-server/scripts/dynamodb:/scripts/dynamodb"
    depends_on:
      - dynamodb
    networks:
      - backend-network

  read-model-updater:
    image: cqrs-es-example-read-model-updater
    container_name: read-model-updater
    platform: linux/arm64
    environment:
      DATABASE_URL: "mysql://DUMMYUSER:DUMMYPASSWORD@mysql:3306/cqrs_es_example"
    expose:
      - "8080"
    depends_on:
      dynamosetup:
        condition: service_completed_successfully
    networks:
      - backend-network

  dynamodb-observer:
    image: cqrs-es-example-dynamodb-observer
    env_file:
      - ./.env/.env.test
    container_name: dynamodb-observer
    platform: linux/arm64
    environment:
      DYNAMODB_HOSTNAME: "dynamodb"
      READ_MODEL_UPDATER_HOSTNAME: "read-model-updater"
    depends_on:
      read-model-updater:
        condition: service_started
    networks:
      - backend-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    platform: linux/amd64 # M1 Mac など ARM アーキテクチャの場合に指定
    environment:
      MYSQL_ROOT_PASSWORD: DUMMYROOTPASSWORD
      MYSQL_DATABASE: cqrs_es_example
      MYSQL_USER: DUMMYUSER
      MYSQL_PASSWORD: DUMMYPASSWORD
      TZ: Asia/Tokyo
    expose:
      - "3306"
    volumes:
      - ./read-api-server/database/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./read-api-server/database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - backend-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "3306:80" # ホストの 8080 → コンテナの 80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
