CREATE TABLE IF NOT EXISTS reservations (
  id VARCHAR(100) PRIMARY KEY,
  user_id VARCHAR(100) NOT NULL,
  table_id VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS tables (
  id VARCHAR(100) PRIMARY KEY,
  user_id VARCHAR(100) NOT NULL,
  reservation_id VARCHAR(100) NOT NULL
);