name: CI for mobile app

on:
  push:
    branches:
      - v3
    paths:
      - "mobile-app/**"
      - ".github/workflows/mobile-app-integration.yml"
  pull_request:
    branches:
      - v3
    paths:
      - "mobile-app/**"
      - ".github/workflows/mobile-app-integration.yml"

jobs:
  mobile-frontend:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mobile-app
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "mobile-app/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Run Frontend Unit Tests
        run: npm run test

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run Component Tests
        run: npm run storybook:ci
  mobile-backend:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mobile-app/src-tauri
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: install dependencies (ubuntu only)
        run: |
          sudo apt-get update 
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy

      - name: Lint Rust Code
        run: cargo clippy -- -D warnings

      - name: Run Backend Unit Tests
        run: cargo test --verbose
