name: CI for read API

on:
  push:
    branches:
      - v3
    paths:
      - "read-api-server/**"
      - ".github/workflows/read-api-integration.yml"
  pull_request:
    branches:
      - v3
    paths:
      - "read-api-server/**"
      - ".github/workflows/read-api-integration.yml"

jobs:
  read-model:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: read-api-server
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install bun
        run: npm install -g bun

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --lockfile-only

      - name: Lint
        run: bun lint

      - name: Genarate prisma client
        run: bun prisma:b

      - name: Run Frontend Unit Tests
        run: bun test
