name: CI for read model updater

on:
  push:
    branches:
      - v3
    paths:
      - "read-model-updater/**"
      - ".github/workflows/read-model-updater-integration.yml"
  pull_request:
    branches:
      - v3
    paths:
      - "read-model-updater/**"
      - ".github/workflows/read-model-updater-integration.yml"

jobs:
  read-model-updater:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: read-model-updater/rust_app
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: install dependencies (ubuntu only)
        run: |
          sudo apt-get update 
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy

      - name: Lint Rust Code
        run: cargo clippy -- -D warnings

      - name: Run Backend Unit Tests
        run: cargo test --verbose
